name: tp-celery-worker

on:
  push:
    branches: [main, develop, mvp/*]
    paths:
      - 'backend/**'

env:
  REGISTRY: docker.io
  CELERY_WORKER_IMAGE: skyryse/tp-celery-worker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CELERY_WORKER_IMAGE }}
          tags: |
            type=raw,value=latest

      - name: Build and push celery worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          target: worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64