name: tp-frontend

on:
  push:
    branches: [main, develop, mvp/*]
    paths:
      - 'frontend/**'
      - 'frontend/admin-dashboard/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - 'frontend/admin-dashboard/**'

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE: skyryse/tp-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FRONTEND_IMAGE }}
          tags: |
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=pr
            type=sha,prefix=commit-
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
            prefix=
            suffix=

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/admin-dashboard/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Update deployment status
        if: github.event_name != 'pull_request'
        run: |
          echo "Frontend image built and pushed successfully"
          echo "Image: ${{ steps.meta.outputs.tags }}"